### ISSUE TITLE
Linux/Mac Compatibility issue in add_sa_role.sh

### ISSUE THREAD

**Issue by aphelionz** [eq-stacks/template-repo#2]
When calling the `date` function at https://github.com/eq-stacks/template-repo/blob/main/scripts/add_sa_role.sh#L6, Linux and Mac will provide different outputs. It works fine on Linux, but when running from a mac it creates a role with an invalid Expiry, which GCP rightly treats as no role at all

**Comment by kkovaacs** [comment]
I've worked this around by just using Python in the empiric-publisher [repo](https://github.com/eq-stacks/empiric-publisher/blob/main/scripts/add_sa_role.sh). Probably not the best solution but at least it behaves the same irrespectively of the underlying OS (more precisely the `date` command).

**Comment by rodriguezcondec** [comment]
Linux uses the GNU version of the date command (hence, GNU/Linux). The equivalent for mac users would be to use [gdate](https://www.freebsd.org/cgi/man.cgi?query=gdate&sektion=&manpath=freebsd-release-ports) instead of `date` to produce the same output regardless of the OS.

That means that we would need to implement a conditional as follows:

```bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        date +%s
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
        gdate +%s
fi
```

Although this could get messy if in the future we decide to use any other OS. Another solution that I found would be to create a symlink between `gdate` to `date` as specified [here](https://stackoverflow.com/questions/15330775/what-does-gdate-mean-in-this-shell-script#answer-36179343) but I'd much rather change the script than to force everyone using Mac to create this symlink.

Nonetheless, I think @kkovaacs suggestion would also work fine!

**Comment by aphelionz** [comment]
I'm happy with whatever so long as the script runs :) python is pretty ubiquitous on all systems, probably should use `python3` explicitly though
